# Generated by Django 6.0.2 on 2026-03-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobantePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acudiente_nombre', models.CharField(max_length=120)),
                ('estudiante_nombre', models.CharField(max_length=120)),
                ('mes_pago', models.CharField(blank=True, help_text='Mes del pago en formato YYYY-MM', max_length=7)),
                ('referencia_factura', models.CharField(blank=True, max_length=80)),
                ('archivo', models.FileField(upload_to='comprobantes/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('comentario_validacion', models.TextField(blank=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
