# Generated by Django 6.0.2 on 2026-03-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('combustible', 'Combustible'), ('mantenimiento', 'Mantenimiento'), ('peajes', 'Peajes'), ('seguros', 'Seguros'), ('otros', 'Otros')], default='otros', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField()),
                ('notas', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='comprobantepago',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor del pago en pesos', max_digits=12),
        ),
    ]
