# Generated by Django 6.0.2 on 2026-03-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_gasto_comprobantepago_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='factura',
            field=models.FileField(blank=True, null=True, upload_to='gastos/facturas/'),
        ),
    ]
