# Generated by Django 6.0.3 on 2026-05-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
