# Generated by Django 6.0.3 on 2026-03-09 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobantepago',
            name='mes_pago',
            field=models.CharField(blank=True, help_text='Mes del pago en formato YYYY-MM', max_length=7),
        ),
    ]
