"""
Django settings for rutasmart_backend project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sqlite3
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent


def _resolve_sqlite_db_path():
    env_path = os.getenv("RUTASMART_DB_PATH")
    if env_path:
        return Path(env_path)

    primary = BASE_DIR / "db.sqlite3"
    fallback = BASE_DIR / "db_backup_try.sqlite3"
    local_appdata = os.getenv("LOCALAPPDATA")
    external_fallback = (
        Path(local_appdata) / "RutaSmart" / "db.sqlite3" if local_appdata else None
    )

    def can_open(path):
        if not path.exists():
            return False
        try:
            connection = sqlite3.connect(path)
            connection.execute("SELECT 1")
            connection.close()
            return True
        except sqlite3.Error:
            return False

    if can_open(primary):
        return primary
    if external_fallback and can_open(external_fallback):
        return external_fallback
    if can_open(fallback):
        return fallback
    return primary

SECRET_KEY = 'change-me'
DEBUG = True
ALLOWED_HOSTS = ['3.222.237.234']

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'students',
    'conductor',
    'vehiculo',
    'finanzas',
    'pagos',
    'ruta',
    'ia',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rutasmart_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rutasmart_backend.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': _resolve_sqlite_db_path(),
    }
}

AUTH_USER_MODEL = 'accounts.User'

LANGUAGE_CODE = 'es-co'
TIME_ZONE = 'America/Bogota'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_URL = 'accounts:login'
LOGOUT_REDIRECT_URL = 'accounts:login'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

GOOGLE_MAPS_API_KEY = os.getenv("GOOGLE_MAPS_API_KEY", "")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
