# Generated by Django 6.0.2 on 2026-03-09 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conductor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('placa', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=200)),
                ('linea', models.CharField(max_length=200)),
                ('modelo', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=50)),
                ('num_asientos', models.PositiveIntegerField()),
                ('combustible', models.CharField(choices=[('gasolina', 'Gasolina'), ('diesel', 'Diésel'), ('electrico', 'Eléctrico'), ('hibrido', 'Híbrido'), ('gas', 'Gas (GNV/GLP)')], max_length=20)),
                ('transmision', models.CharField(choices=[('manual', 'Manual'), ('automatica', 'Automática'), ('cvt', 'CVT'), ('dct', 'Doble embrague (DCT)')], max_length=20)),
                ('cilindraje', models.PositiveIntegerField(blank=True, null=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='conductor.conductor')),
            ],
        ),
    ]
