# Generated by Django 6.0.3 on 2026-05-12 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='num_asientos',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(4)]),
        ),
    ]
